
---
apiVersion: v1
kind: Namespace
metadata:
  name: test-pipeline
---
apiVersion: v1
kind: Service
metadata:
  name: weather
  annotations:
        prometheus.io/scrape: 'true'
  labels:
    name: weather
  namespace: test-pipeline
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    name: weather