
---
apiVersion: v1
kind: Namespace
metadata:
  name: test-pipeline
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather
  namespace: test-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      name: weather
  template:
    metadata:
      labels:
        name: weather
    spec:
      containers:
      - name: weather
        image: weaveworksdemos/weather:0.3.12
        resources:
          limits:
            cpu: 300m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 300Mi
        ports:
        - containerPort: 8079
        env:
        - name: SESSION_REDIS
          value: "true"
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          runAsUser: 10001
          capabilities:
            drop:
              - all
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /
            port: 8079
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8079
          initialDelaySeconds: 30
          periodSeconds: 3
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: weather
  annotations:
        prometheus.io/scrape: 'true'
  labels:
    name: weather
  namespace: test-pipeline
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8079
    nodePort: 30001
  selector:
    name: weather